version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_PASSWORD=root
  docker-compose-demo:
    build: .
    image: docker-compose-demo
    depends_on:
    - docker-mysql
    ports:
    - 8081:8080
